### ISSUE TITLE
Is PATIENT_ID unique in tb_patients?

### ISSUE THREAD

**Issue by lknegendorf** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#12]
- Are there patients with more than one disease?
- Is patient_id used for different patients in the datasets?

**Comment by Carmen-Haubold** [comment]
Hi Leo, hi Felix,

I'm still working on the sql-statement, but the table is not output in python.
Where is the mistake in this python-statement?

Thank you

Greetings Carmen


#SQL_Abfrage_patient_Id_unique
import sqlite3
connection = sqlite3.connect('/content/gdrive/Shareddrives/IMECOS/imecos.db')
cursor = connection.cursor()
sql = "SELECT Id FROM tb_patients"
#"SELECT Id FROM tb_patients"\
#"WHERE Id IS NOT NULL"\
#"GROUP BY Id"
print(sql)
cursor.execute(sql)
connection.close()

**Comment by lknegendorf** [comment]
> Hi Leo, hi Felix,
> 
> I'm still working on the sql-statement, but the table is not output in python.
> Where is the mistake in this python-statement?
> 
> Thank you
> 
> Greetings Carmen
> 
> #SQL_Abfrage_patient_Id_unique
> import sqlite3
> connection = sqlite3.connect('/content/gdrive/Shareddrives/IMECOS/imecos.db')
> cursor = connection.cursor()
> sql = "SELECT Id FROM tb_patients"
> #"SELECT Id FROM tb_patients"
> #"WHERE Id IS NOT NULL"
> #"GROUP BY Id"
> print(sql)
> cursor.execute(sql)
> connection.close()


Hi @Carmen-Haubold ,

die Datenbank wird in der Datei  [source_database_implementation.py](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/source_database_implementation.py) schon komplett fertig vorgenommen.
Du brauchst also die kompletten Zeilen nicht.
`import sqlite3`
`connection = sqlite3.connect('/content/gdrive/Shareddrives/IMECOS/imecos.db')`
`cursor = connection.cursor()`

Kurz zur Erklärung vielleicht, ein kleines Beispiel von mir:
Wenn du dir vorstellest eine Datenbank ist ein Kellerraum mit verschiedenen Ordnern drin, in denen Informationen auf einzelnen Zetteln abgeheftet sind, dann ist die Verbindung zu einer Datenbank in Python so, als hättest du Ordner, die du gerne in einem Keller abstellen würdest. Du selber hast aber keinen Keller, deswegen fragst du eine Freundin, bei der im Haus ein Keller frei ist und sie hat einen sehr netten Vermieter, der sicher erlaubt, dass du da Dinge kurzfristig abstellst.
In der Datei [source_database_implementation.py](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/source_database_implementation.py) passiert nun folgendes:
`# SQLite connection`
`def create_connection_memory():`
  `conn = None;`
  `try:`
    `#Establishing the connection`
    `conn = sq.connect(':memory')`
    `return conn`
    `print(sqlite3.version)`
  `except Error as e:`
    `print("Error while connecting to sqlite", e)`
Hier wird zunächst eine Methode definiert, die die Datenbank verbindet. In unserem anschaulichen Beispiel also überlegt man sich vorher, wie man wohl den Vermieter um Erlaubnis fragen kann, dass sein Kellerraum genutzt werden darf. 
Neben dem Handling von Fehlern (Try-Catch-Klausel, also bei `try` sagt der Vermieter ja und bei `catch` sagt der Vermieter nein) was die Methode etwas kompliziert erscheinen lässt ist eigentlich nur diese Anweisung daraus wichtig:
`conn = sq.connect(':memory')`
Hier wird die Verbindung zu einer Datenbank aufgebaut, die sich im Zwischenspeicher befindet.
(Auch wenn es nicht zu 100% richtig ist, kann man für die Anschaulichkeit des Beispiel sagen, dass `conn` der Vermieter ist)
Im Code wird also bei Verwendung der vorher definierten Methode, also
`conn = create_connection_memory()`
der Vermieter nun tatsächlich um Erlaubnis gefragt und er gibt auch die Erlaubnis.
Nur weil er die Erlaubnis gegeben hat, kannst du deine Ordner ja jetzt noch nicht unterstellen, du brauchst noch den Schlüssel für den Kellerraum.
`cur = conn.cursor()`
Vereinfacht gesagt, bekommt hier deine Freundin vom Vermieter den Schlüssel zum Kellerraum und hat nun Zugriff darauf, also `cur` ist deine Freundin, die den Schlüssel hat (du selber hast ja gar kein Mietverhältnis in dem Haus und deswegen hast du gar keinen Schlüssel zum Kellerraum).
Nun gibt es immer zwei Möglichkeiten

1. Du möchtest neue Ordner in den Keller stellen.
Hier kannst du deiner Freundin sagen, welche Ordner sie in den Keller stellen soll mit
`cur.execute("hier steht irgendein SQL-Statement")`
wenn noch neue Sachen dazu kommen, muss aber der Vermieter immer noch sein OK geben, man will ja nicht die ganze Hand nehmen, wenn der nette Vermieter schon seinen kleinen Finger angeboten hat. Man braucht also immer noch ein
`conn.commit()`.

2. Wenn du einfach nur wissen möchtest, welche Informationen in deinen Ordnern stehen, geht das so wie in der Testabfrage:
`# Testabfrage`
`cur.execute("""SELECT *`
               `FROM tb_payer_transitions""")`
`testabfrage = cur.fetchall()`
`for row in testabfrage:`
  `print(row)`
Also du rufst deine Freundin an, und sagst ihr zuerst, wonach sie suchen soll mit
`cur.execute("""SELECT *`
               `FROM tb_payer_transitions""")`
Wenn sie jetzt gefunden hat, was du meinst, siehst du ja noch nicht, was auf der Seite im Ordner steht (du bist ja nicht da, sondern hast die Freundin nur am Telefon). Also musst du ihr sagen, dass sie dir das vorlesen soll. `cur.fetchall()` heißt, sie soll dir alles Vorlesen, was darauf steht, es gibt auch die Möglichkeit schon hier zu sagen, dass sie dir nur einen Teil vorlesen soll.
Weil du dir ja nicht alles auf einmal merken kannst, was dir deine Freundin am Telefon vorliest, wenn es eine komplette Seite ist, bittest du sie, ein Foto davon zu machen, dann kann sie sich gemütlich auf ihr Sofa setzen und dir vom Foto alles vorlesen.
`testabfrage = cur.fetchall()`
Die Variable `testabfrage` ist jetzt also das Foto von dem, was die Freundin rausgesucht hatte. Jetzt sagst du ihr mit
`for row in testabfrage:`
  `print(row)`, dass sie dir immer nur eine Zeile vorlesen soll, und erst dann eine weitere Zeile.
Noch wichtiger, dass sie ein Foto macht (also, dass das Ergebnis in einer Variable gespeichert wird) ist es, wenn du sie danach noch eine zweite Sache fragst, weil dann muss sie ja einen anderen Ordner rausnehmen und kann dann wieder nur das vorlesen, was in dem neuen Ordner steht.

Ich hoffe das Beispiel war jetzt nicht zu weit hergeholt. Du kannst also für die Bearbeitung der Issues jetzt einfach die Testabfrage in Colabbook kopieren und dein gewünschtes SQL Statement reinschreiben und vielleicht die Variable `testabfrage` anders benennen. Es geht also hier nur drum, die richtigen SQL-Abfragen einzusetzen, alles andere funktioniert bereits.

**Comment by fphans** [comment]
Klasse Tutorial Leo!

habe das Masterfile etwas entschlackt und Deine Abfrage @Carmen-Haubold entsprechend ergänzt. komischer weise commite ich das dann in den branch_felix, es gibt aber keine pull requests an euch weil git sagt es gäbe nichts zu vergeleichen...

So ich bin jetzt fast wieder in Freiburg, 

Cheers an alle!

**Comment by Carmen-Haubold** [comment]
Hallo Leo,

vielen Dank für die ausführliche und gute Erklärung. Colab meldet mir die
Fehlermeldung "OperationalError: no such table: patients"
Entweder habe ich nicht den richtigen Tabellennamen eingegeben (habe es
auch mit "tb_patients" probiert, hat nicht funktioniert) oder ich mache
einen anderen Fehler.
Kannst du nachvollziehen woran es liegt?

Vielen Dank.

Grüße Carmen

**Comment by fphans** [comment]
Hi Carmen,

Guck mal in das masterfile da habe ich eine funktionierende version hinterlassen.

Lg

Felix

Sent securely from Check Point Capsule Workspace

**Comment by Carmen-Haubold** [comment]
Hi Felix,

herzlichen Dank. Die SQL-Abfrage gibt Null doppelte Patienten-ID aus.

LG Carmen

Am Sa., 23. Jan. 2021 um 23:32 Uhr schrieb fphans <notifications@github.com
