### ISSUE TITLE
Add table documentation to wiki

### ISSUE THREAD

**Issue by lknegendorf** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#2]
Create one page per table. This page should contain the following information.
   SQL Create Statement
   Table with the following columns

-         Column designation,
-         Column data type,
-         Columns content description,
-         Is there an index for this column? If so what is the index name, what is the index type
-         Is this column connected to another table via a foreign key constraint? If so, link to the other table documentation.

**Comment by fphans** [comment]
ok ist #2 das was in das Dtenmodell III soll?

**Comment by lknegendorf** [comment]
> ok ist #2 das was in das Dtenmodell III soll?

YES ;)

**Comment by fphans** [comment]
Hola @Carmen-Haubold und @lknegendorf ,

die Tabellen sind jetzt alle erstellt. Was jetzt noch das Sahnehäubchen wäre wenn alle Schlüsselbeziehungen die Links auf die referenzierte Tabelle enthalten wir z.b. in [tb_careplans](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Tabellenkonfiguration-%60tb_careplans%60) exemplarisch. Das ist aber ein mords aufwand. was meint Ihr?

Leo hatte richtigerweise auch noch genauere descriptions angemahnt, auch hier bitte Stimmungsbild und umsetzungsvorchlag.

lg fx

**Comment by Carmen-Haubold** [comment]
Hola,

eine Referenz zur Tabelle finde ich gut.
Vielleicht können wir morgen über die Beschreibung sprechen?

LG Carmen

fphans <notifications@github.com> schrieb am Di. 2. Feb. 2021 um 21:21:

**Comment by lknegendorf** [comment]
Hab die Referenzlinks bei den Foreign Keys alle wie besprochen umgesetzt. 
Habe beim [Quelldatenmodell](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell) noch einen Hinweis zu den fehlenden Spaltenbeschreibungen ergänzt.

Damit; CHECK
