### ISSUE TITLE
Are transformations needed for the data we use?

### ISSUE THREAD

**Issue by lknegendorf** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#24]

**Comment by lknegendorf** [comment]
If so, we need to do the transformations

**Comment by lknegendorf** [comment]
As already explained in the documentation (see [here](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Model-of-Source-Data---III) the datasets COVID-19 and ALLERGY contain duplicate valued in both TB_OBSERVATIONS and TB_SUPPLIES

- [ ] Remove duplicates from TB_OBSERVATIONS
- [ ] Remove duplicates from TB_SUPPLIES

**Comment by fphans** [comment]
ist das nicht durch das AUTO_Increment gelöst

**Comment by lknegendorf** [comment]
> ist das nicht durch das AUTO_Increment gelöst

Ne dadurch besteht das Problem ja weiter, die Daten lassen sich nur in die Datenbank laden.
Die Duplikate bei Observations lassen sich bspw. über eine AVG-Aggregatfunktion,
die in supplies über eine SUM-Aggregatfunktion lösen, wäre meine spontane Antwort.

**Comment by lknegendorf** [comment]
> As already explained in the documentation (see [here](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Model-of-Source-Data---III) the datasets COVID-19 and ALLERGY contain duplicate valued in both TB_OBSERVATIONS and TB_SUPPLIES
> 
> * [x]  Remove duplicates from TB_OBSERVATIONS
> * [x]  Remove duplicates from TB_SUPPLIES

Beide Tabellen werden nicht gebraucht (vgl. #30, #16 und folgende)

**Comment by lknegendorf** [comment]
- [x] Anpassung Datumswerte (teilw. timestamp, date oder year(als int) -> Einheitliche Werte für Sternschema

**Comment by lknegendorf** [comment]
Check
