### ISSUE TITLE
Vereinheitlichung der Sprache im Wiki - Einigung auf Sprache DEUTSCH

### ISSUE THREAD

**Issue by lknegendorf** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#27]
Alle bisherigen englischen Inhalte müssen auf deutsch übersetzt werden.

**Comment by fphans** [comment]
Bezieht sich das auch die kommentare im Code? das Wiki und die Links habe ich mal bereinigt. Im Code fände ich kommentare wie 'import libraries' legitin.

was meint ihr?

**Comment by lknegendorf** [comment]
> Bezieht sich das auch die kommentare im Code? das Wiki und die Links habe ich mal bereinigt. Im Code fände ich kommentare wie 'import libraries' legitin.
> 
> was meint ihr?

Ja finde ich auch vollkommen ok.

**Comment by fphans** [comment]
ok hatte die anderen seiten nicht gesehen - bin dran

**Comment by fphans** [comment]
bitte hilfe bei der übersetzung für:

Non-conservative primary keys including various attributes where no 'Id' attribute is specified

**Comment by fphans** [comment]
@lknegendorf : wolltest Du [hier](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell---III) am ende die Views auf die Tabellen verlinken oder was hattest Du dir vorgestellt?

**Comment by lknegendorf** [comment]
> bitte hilfe bei der übersetzung für:
> 
> Non-conservative primary keys including various attributes where no 'Id' attribute is specified

Erledigt!

**Comment by lknegendorf** [comment]
> @lknegendorf : wolltest Du [hier](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell---III) am ende die Views auf die Tabellen verlinken oder was hattest Du dir vorgestellt?

Da müssen noch die Erklärungen zu den einzelnen Spalten rein, wie [hier im Synthea wiki](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary#medications). Das wird aber in Aufgabe #2 gefordert. Also hier erstmal fertig
