### ISSUE TITLE
Create seperate Text files with the SQL statements

### ISSUE THREAD

**Issue by lknegendorf** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#3]
To do this, create SQL Create Statements

-     Create indexes on the columns that are often used for searching.
-     Create foreign key constraints to link the CSV files together

**Comment by Carmen-Haubold** [comment]
### Tabelle careplans

`create table tb_careplans (
Id varchar (256) default NULL,
START varchar (256) DEFAULT NULL,
STOP date (10) DEFAULT NULL,
PATIENT varchar (256) PRIMARY key not NULL,
ENCOUNTER varchar (256) default NULL,
CODE varchar (256) default NULL,
DESCRIPTION VARCHAR (256) DEFAULT NULL,
REASONCODE varchar (256) DEFAULT NULL,
REASONDESCRIPTION VARCHAR (256) DEFAULT NULL);`

**Comment by lknegendorf** [comment]
Hey @Carmen-Haubold, great work so far! I saw you closed the issue, was this intended or are you still working on it? I could assign the card on [our board](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/projects/1) accordingly if you want me to 💯

**Comment by Carmen-Haubold** [comment]
Hi,

ich habe nur erstmal ein bisschen geübt. Das geht natürlich noch weiter.

Gruß Carmen

Am Mi., 13. Jan. 2021 um 16:01 Uhr schrieb lknegendorf <
notifications@github.com>:

**Comment by lknegendorf** [comment]
Alright, reopening because progress is still going on here 👍

**Comment by fphans** [comment]
würde die Tabellen in Colab dann so erstellen wenn Ihr einverstanden Seid:

https://colab.research.google.com/drive/17kSsfhvEfuZmjQAcQqNRy_kcWIxiQsvY#scrollTo=3TqXCHs26N_9&line=3&uniqifier=1
