### ISSUE TITLE
Mir ist unklar wie Quelldatenmodell I-III zusammenhängt

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#34]
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell-I
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell--II
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell---III

* Ich würde vorschlagen entweder ein Dokument aus den 3 Seiten zu erstellen oder das die Bezeichnung der Quelldatenmodell Seiten mehr sagt was dort dokumentiert ist.

* Was mir fehlt ist die Dokumentation des Tabellen schemas. Die könnt ihr aus der Synthea Seite auch kopieren.\
vielleicht ist das ja auf der Seite Quelldatenmodell III vorgesehen.
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell---III
Hier werden Tabellen Dokumentationen referenziert die noch nicht vorhanden sind.

Takehome message: Konsolidiert die 3 Seiten in eine und verlinkt diese im Datenmanagementplan

**Comment by lknegendorf** [comment]
Seiten Quelldatenmodell I-III wurden durch @fphans zu einer Seite konsolidiert.
Dokumentation des Tabellenschemas ist mit Abschluss von #2 erledigt.
