### ISSUE TITLE
ETL Doku

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#35]
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenbereinigung-im-ETL-Prozess

Hier Fehlt meiner Meinung nach eine Mapping Tabelle
## Tabellen name (Stern Schemas)
| Spalten Name| Typ | Beschreibung| QuellDatenbank | Quelltabelle| QuellSpalte|
|-------------- |-----|--------------|-----------------|-------------|------------|
| Diagnose Code| String| Snomed Diagnose Code|  SourceDB| Procedures| Code|

Eure Analysen zu Redundanzen und Unstimmigkeit würde ich in eine neue Seite Stellen. Dies gehört zum Thema Datenqualität.

Eure ETL Seite sollte links auf euren ETL Code im Git repository enthalten.
Am besten Dokumentiert ihr eure ETL Jobs unter der Tabelle die diese ETL Jobs aufbauen.

**Comment by fphans** [comment]
@Carmen-Haubold , wolltest Du diese Mappingtabelle erstellen?

**Comment by fphans** [comment]
ETL-Dateipfade eingepfelgt unter [ETL](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenbereinigung-im-ETL-Prozess) und [Clearing](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenqualit%C3%A4t)

passt das so?

**Comment by fphans** [comment]
[Mappingtbl](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Mapping-Tabelle)


damit schliessen?

**Comment by fphans** [comment]
Link auch in der Sidebar eingepflegt

**Comment by Carmen-Haubold** [comment]
![tb_patients](https://user-images.githubusercontent.com/77020590/107081421-f24fe180-67f2-11eb-87e5-5d45a8ba90b0.jpg)

Hi,
ich wollte mal fragen, ob in der Tabelle tb_patients, Spalte "COV_EXP_RATIO", was die Quellspalte ist und was man in der Beschreibung schreiben könnte?

Vielen Dank.

Grüße Carmen

**Comment by lknegendorf** [comment]
> ![tb_patients](https://user-images.githubusercontent.com/77020590/107081421-f24fe180-67f2-11eb-87e5-5d45a8ba90b0.jpg)
> 
> Hi,
> ich wollte mal fragen, ob in der Tabelle tb_patients, Spalte "COV_EXP_RATIO", was die Quellspalte ist und was man in der Beschreibung schreiben könnte?
> 
> Vielen Dank.
> 
> Grüße Carmen

Das ist ein Quotient aus den Spalten HEALTHCARE_COVERAGE und HEALTHCARE_EXPENSES, man könnte schreiben, dass es ein Score zwischen 0 und 1 ist, der den Anteil der versicherten Gesundheitskosten eines Patienten angibt o.ä.

BG, Leo

**Comment by Carmen-Haubold** [comment]
Vielen Dank.

**Comment by lknegendorf** [comment]
Top, danke! Eine Anmerkung noch, im Data Warehouse, also der "Forschungsdatenbank" haben die Tabelle nicht das Präfix 'tb_', also z.B. einfach nur 'encounters'. Das ist damit bei der Bezeichnung klar ist, ob die Source DB oder das Data Warehouse gemeint ist.

**Comment by Carmen-Haubold** [comment]
Du meintest hier im Navigationsmenü und in den Tabellenbezeichnungen? -> da habe ich es jetzt korrigiert

![Mappingtabelle_Sideboard](https://user-images.githubusercontent.com/77020590/107085884-65f4ed00-67f9-11eb-8784-cc7895e02e1a.jpg)

![Mappingtabelle_Tabelle](https://user-images.githubusercontent.com/77020590/107085887-668d8380-67f9-11eb-8799-afd6498eceed.jpg)

**Comment by lknegendorf** [comment]
> Du meintest hier im Navigationsmenü und in den Tabellenbezeichnungen? -> da habe ich es jetzt korrigiert
> 
> ![Mappingtabelle_Sideboard](https://user-images.githubusercontent.com/77020590/107085884-65f4ed00-67f9-11eb-8784-cc7895e02e1a.jpg)
> 
> ![Mappingtabelle_Tabelle](https://user-images.githubusercontent.com/77020590/107085887-668d8380-67f9-11eb-8799-afd6498eceed.jpg)

YES! Great!
