### ISSUE TITLE
Noch ein paar links für eure Auswertung

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#37]
Plot links  (könnt ihr nach inspiration suchen https://seaborn.pydata.org/examples/index.html oder https://matplotlib.org/3.1.1/gallery/index.html)  
machine learninglinks (hier werden verschiedene Classifier dargestellt https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html oder https://scikit-learn.org/stable/supervised_learning.html)

**Comment by fphans** [comment]
![grafik](https://user-images.githubusercontent.com/77018941/106658661-da335480-659d-11eb-9dd0-f395dcb6bf29.png)

**Comment by fphans** [comment]
![grafik](https://user-images.githubusercontent.com/77018941/106667579-639c5400-65a9-11eb-8715-8ec08e9256ad.png)

**Comment by lknegendorf** [comment]
@fphans hat sich das Problem mit der kleineren Tabelle als Basis gelöst?

**Comment by fphans** [comment]
das prüfe ich nochmal, denke aber das issue kann zu.
