### ISSUE TITLE
kontrolle kontaktdaten

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#40]
@Carmen-Haubold @lknegendorf bitte [Hier](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenmanagementplan) Euer kontaktdaten prüfen und freigeben bitte

**Comment by lknegendorf** [comment]
Erledigt ;)

**Comment by fphans** [comment]
@Carmen-Haubold , hinterlegst Du hier noch was oder soll ich das Tickt schliessen?

**Comment by Carmen-Haubold** [comment]
Die Tabelle ist noch in Bearbeitung.
Das Ticket bitte noch offen lassen.

fphans <notifications@github.com> schrieb am Di. 2. Feb. 2021 um 21:09:

**Comment by fphans** [comment]
bleibt spannend ;-) @Carmen-Haubold

**Comment by fphans** [comment]
hi @Carmen-Haubold ich schliesse mal das ticket. Du kannst Ja jederzeit etwas ergänzen wenn du noch magst.
