### ISSUE TITLE
tb_table specs

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#41]
@lknegendorf @Carmen-Haubold 

bitte prüfen:

[tb_patients](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Model-of-Source-Data---tb_patients)

brauchen iwr unter der zeitwn überschrift noch eine table.info ausgabe?

**Comment by lknegendorf** [comment]
Passt soweit, @fphans würde ich sagen. Ne table.info brauchen wir m.E. nicht, das ist ja schon Datenanalyse und den Großteil der Attribute dort laden wir ja auch gar nicht in unser Data Warehouse.
Aber ich denke wir sollten in der Tabelle noch eine Spalte Beschreibung ergänzen, wo wir in ein paar kurzen Stichworten beschreiben, welche Daten in dem Atttribut abgebildet werden (auch wenn es teilweise durch die Benennung offensichtlich ist).
So wie hier im [synthea wiki](https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary).

**Comment by fphans** [comment]
Gute Idee, allerdings sehr zeitaufwändig. Habe jetzt Immerhin mal alle tabellen Fertig

**Comment by lknegendorf** [comment]
> Gute Idee, allerdings sehr zeitaufwändig. Habe jetzt Immerhin mal alle tabellen Fertig

Wollten wir ja weglassen, ist gemeinsam mit #34 dann ja auch abgehakt.
