### ISSUE TITLE
schlüsselattribute

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#42]
bitte prüfen ob notation der fremdschlüsslebeziehungen so passt. für meine begriffe müsste primary key dann weg wenns ein fremdschlüssel ist

es geht um die TB_ tabellen im quelldatenmodell

**Comment by lknegendorf** [comment]
Passt alles was ich bisher gesehen habe, @fphans . Die die noch nicht in tabellenform sind, habe ich noch nicht so genau angeguckt.
Da wo ein Fremdschlüssel auch Teil des Primärschlüssels ist, ist das so gewollt und richtig angegeben.

**Comment by fphans** [comment]
Ok danke für die Rückmeldung!
