### ISSUE TITLE
Dokumentation der Systemumgebung

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#44]
Hi,
Ihr solltet noch eine Extra Seite zur Dokumentation der System Umgebung anlegen.

Hier geht es um:

1.  Aufbewahrungsort der Daten (Google DOCS)
      a. Google Server
      b. Das backup und die Sicherheit wird von google gewährleistet
2. System Umgebung in denen der Code ausgeführt wird
     a. Dokumentation der Dependencies wie in dem Video demonstriert
     b. Ausführungsort Docker Container auf Google Servern

Verlinkt das Dokument auch in den Datenmanagmentplan

**Comment by lknegendorf** [comment]
Im Quelldatenmodell sind ja die Original-.csv Dateien verlinkt, hier muss ein Hinweis rein, dass diese nur zugänglich für die Mitarbeitenden des Projektes sind, da sie ja die Patientendaten enthalten.

**Comment by fphans** [comment]
Seite ist erstellt und mit Rohentwurf befüllt. Teilweise aber unklar was da alles rein muss / fehlt

**Comment by fphans** [comment]
[Systemumgb](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/System-Umgebung)

@Carmen-Haubold , kannst Du was zu den Dependencies finden?

**Comment by fphans** [comment]
@lknegendorf kannst Du hier Freigabe erteilen (bis auf dependencies, dann mahcen wir den issue zu wenn das ergänzt ist

**Comment by Carmen-Haubold** [comment]
Hallo Felix,

Dependecies sind Abhängigkeiten von einer anderen Software oder Bibliothek (ColabBook?, seaborn?).

https://www.dev-insider.de/was-ist-eine-dependency-a-899057/

**Comment by fphans** [comment]
Hi Carmen,

danke für die Antowort. Ich hatte gestern so verstanden als hast du das video schon gesehene (was ich nicht finde). Könntest Du das exzerpieren?


Mit freundlichen Grüßen

Felix

**Comment by Carmen-Haubold** [comment]
Hi Felix,

ich hatte nur das Video zur Datenschutzfolgeabschätzung gesehen. Da ist es
aber nicht dabei. Zu dem Punkt habe ich etwas notiert, schaue mir aber die
Datenbank nochmal genauer an um noch etwas ergänzen zu können.

Grüße Carmen

fphans <notifications@github.com> schrieb am Sa. 6. Feb. 2021 um 18:27:

**Comment by lknegendorf** [comment]
> @lknegendorf kannst Du hier Freigabe erteilen (bis auf dependencies, dann mahcen wir den issue zu wenn das ergänzt ist

Zu diesem Punkt: Das Backup und die Sicherheit wird durch das Google-System selbst gewährleistet

Kann man hier noch was schlaues aus den Nutzungsbedingungen von Google finden, was das konkretisiert? Inwiefern haftet Google für Datenverlust etc.?

**Comment by lknegendorf** [comment]
> [Systemumgb](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/System-Umgebung)
> 
> @Carmen-Haubold , kannst Du was zu den Dependencies finden?

Zu den Dependencies können wir erst was schreiben, wenn wir die neue Datenbank haben (darum kümmere ich mich gleich noch), das können wir dann mit einem anderen Google Account testen.
Zum jetzigen Zeitpunkt kann man auf jeden Fall schon reinschreiben, dass es notwendig ist, einen Google Account zu besitzen.

**Comment by Carmen-Haubold** [comment]
Ok. Ich habe es korrigiert.

lknegendorf <notifications@github.com> schrieb am Sa. 6. Feb. 2021 um 18:50:

**Comment by lknegendorf** [comment]
> > [Systemumgb](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/System-Umgebung)
> > @Carmen-Haubold , kannst Du was zu den Dependencies finden?
> 
> Zu den Dependencies können wir erst was schreiben, wenn wir die neue Datenbank haben (darum kümmere ich mich gleich noch), das können wir dann mit einem anderen Google Account testen.
> Zum jetzigen Zeitpunkt kann man auf jeden Fall schon reinschreiben, dass es notwendig ist, einen Google Account zu besitzen.

Es muss folgende Anleitung rein:

Öffentlicher Link zur Datenbank: https://drive.google.com/file/d/1cnzmvXIE7CDIULh8hIHPCZJKEI4RKTiX/view?usp=sharing

1) Link öffnen
2) In der oberen rechten Ecke "Verlinkung zum Drive hinzufügen" klicken (Google Drive Symbol)
3) "Meine Ablage" auswählen
4) Auswahl durch klicken des Buttons "Verknüpfung hinzufügen" bestätigen
5) Es erscheint eine Meldung zur Bestätigung

Nun ist das Colabbook ausführbar "Initialisierung für die Öffentlichkeit" oder wie ich das genannt habe muss ausgeführ werden.
Als Hinweis zur Systemumgebung: Es kann nur funktionieren, wenn die Datenbank in das Root-Verzeichnis von Meine Ablage wie in Punkt 3 der Anleitung beschrieben verlinkt wird. (Hab es technisch aber so gebaut, dass ich den Umstand noch leicht ändern kann, falls es Max nicht gefällt (Dann müsste der Nutzer den Pfad in seinem Drive vorher eingeben).

@Carmen-Haubold @fphans würde einer von euch das in schön auf der entprechenden Seite einpflegen? :) Weiß nicht, wer die jetzt hauptverantwortlich betreut hat.

**Comment by Fuenfgeld** [comment]
https://youtu.be/_TjRcghwdxg
Hier ist das Video

**Comment by lknegendorf** [comment]
> https://youtu.be/_TjRcghwdxg
> Hier ist das Video

Top DANKE!

**Comment by lknegendorf** [comment]
@fphans @Carmen-Haubold habe mal einen Umsetzungsvorschlag für die Dokumentation angefertigt.
Siehe hier im [Wiki/System-Umgebung](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/System-Umgebung)
