### ISSUE TITLE
Datenschutz Folgeabschätzung

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#45]
Legt die Datenschutz Folgeabschätzung in einer neuen Seite an und Verlinkt diesen im Datenmanagementplan

**Comment by fphans** [comment]
@Carmen-Haubold stellst Du diese Vorlage ein?

**Comment by Carmen-Haubold** [comment]
Ja, mache ich.

fphans <notifications@github.com> schrieb am Fr. 5. Feb. 2021 um 17:27:

**Comment by fphans** [comment]
done
