### ISSUE TITLE
Datenmanagement Plan enthält noch Satzbausteine aus dem Template

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#46]
Geht  über euren DM und überarbeitet ihn nochmal sodass er auf euer Projekt passt.

Außerdem müssen die Haupt Wiki Seiten dort als Link auftauchen

**Comment by fphans** [comment]
![grafik](https://user-images.githubusercontent.com/77018941/107067388-81eb9500-67df-11eb-8dc5-cffb942b95a9.png)

**Comment by lknegendorf** [comment]
Mein Vorschlag:

### Übersicht GitHub Repository [`Fuenfgeld/ATeamDatenmanagementUndArchivierung`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung)

Pfad | Dateiname | Sprache/Dateiformat | Ausführungsumgebung | Datenzugriff | Zweck
----- | ----- | ----- | ----- | ----- | -----
. | [`IMECOS_master.ipynb`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb) | Jupyter Notebook | Google Colab | Quelldaten und Öffentliche Daten möglich | Colab Book Masterfile ([System-Umgebung](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/System-Umgebung))
. | [`LICENSE`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/LICENSE) | | GitHub | | Repository Lizenz: MIT License
. | [`README.md`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/README.md) | Markdown Language | GitHub | | Repository Readme
`build/` | .gitignore | | GitHub | | GitHub Systemdatei
`docs/` | [`ER_model_of_data_warehouse.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ER_model_of_data_warehouse.svg) | Scalable Vector Graphics | Einbindung in Wiki | | Graphische Dokumentation
`docs/` | [`ER_model_of_source_data.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ER_model_of_source_data.svg) | Scalable Vector Graphics | Einbindung in Wiki | | Graphische Dokumentation
`docs/` | [`ETL_Mapping.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ETL_Mapping.svg) | Scalable Vector Graphics | Einbindung in Wiki | | Graphische Dokumentation
`docs/` | [`ETL_view_on_source_data.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ETL_view_on_source_data.svg) | Scalable Vector Graphics | Einbindung in Wiki | | Graphische Dokumentation
`img/plots/` | [`COV_EXP_distribution_by_disease.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/COV_EXP_distribution_by_disease.png) | Portable Network Graphics | Einbindung in Wiki | | Ergebnisse von Datenanalysen
`img/plots/` | [`COV_EXP_outlier.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/COV_EXP_outlier.png) | Portable Network Graphics | Einbindung in Wiki | | Ergebnisse von Datenanalysen
`img/plots/` | [`ENCOUNTERCLASS_by_disease.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/ENCOUNTERCLASS_by_disease.png) | Portable Network Graphics | Einbindung in Wiki | | Ergebnisse von Datenanalysen
`src/` | [`public_datawarehouse_connection.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/public_datawarehouse_connection.py) | Python | Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb) | Öffentliche Daten | Datenbankinitialisierung Öffentlichkeit ([Data Warehouse](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Mappingtabelle_Gesamt))
`src/` | [`source_database_implementation.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/source_database_implementation.py) | Python | Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb) | Quelldaten |  Datenbankinitialisierung Projektverantwortliche ([Source DB](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#datenbank-implementierung))
`tools/` | [`ETL_create_view_central.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/ETL_create_view_central.sql) | SQL | Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb) | Quelldaten | Datenbankinitialisierung Projektverantwortliche ([ETL-Prozess](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenbereinigung-im-ETL-Prozess))
`tools/` | [`ETL_process.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/ETL_process.py) | Python | Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb) | Quelldaten (Öffentliche Daten werden erzeugt) | Datenbankinitialisierung Projektverantwortliche ([ETL-Prozess](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenbereinigung-im-ETL-Prozess))
`tools/` | [`create_statements_source_db.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/create_statements_source_db.sql) | SQL | Einbindung in [`source_database_implementation.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/source_database_implementation.py) | Quelldaten | Datenbankinitialisierung Projektverantwortliche ([Source DB](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#datenbank-implementierung))
`tools/` | [`data_clearing_SQL_queries.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/data_clearing_SQL_queries.py) | Python | Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb) | Quelldaten | Dokumentation [Datenqualität](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenqualit%C3%A4t#identifikation-von-redundanzen-und-unstimmigkeiten---data-clearing)
`tools/` | [`data_quality_delete_outlier.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/data_quality_delete_outlier.sql) | SQL | Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb) | Öffentliche Daten | [Datenqualität](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenqualit%C3%A4t#identifikation-von-fehlern-und-ausrei%C3%9Fern-in-der-datenbasis---preliminary-data-analysis)

**Comment by lknegendorf** [comment]
> Mein Vorschlag:
> 
> ### Übersicht GitHub Repository [`Fuenfgeld/ATeamDatenmanagementUndArchivierung`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung)
> Pfad	Dateiname	Sprache/Dateiformat	Ausführungsumgebung	Datenzugriff	Zweck
> .	[`IMECOS_master.ipynb`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Jupyter Notebook	Google Colab	Quelldaten und Öffentliche Daten möglich	Colab Book Masterfile ([System-Umgebung](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/System-Umgebung))
> .	[`LICENSE`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/LICENSE)		GitHub		Repository Lizenz: MIT License
> .	[`README.md`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/README.md)	Markdown Language	GitHub		Repository Readme
> `build/`	.gitignore		GitHub		GitHub Systemdatei
> `docs/`	[`ER_model_of_data_warehouse.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ER_model_of_data_warehouse.svg)	Scalable Vector Graphics	Einbindung in Wiki		Graphische Dokumentation
> `docs/`	[`ER_model_of_source_data.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ER_model_of_source_data.svg)	Scalable Vector Graphics	Einbindung in Wiki		Graphische Dokumentation
> `docs/`	[`ETL_Mapping.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ETL_Mapping.svg)	Scalable Vector Graphics	Einbindung in Wiki		Graphische Dokumentation
> `docs/`	[`ETL_view_on_source_data.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ETL_view_on_source_data.svg)	Scalable Vector Graphics	Einbindung in Wiki		Graphische Dokumentation
> `img/plots/`	[`COV_EXP_distribution_by_disease.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/COV_EXP_distribution_by_disease.png)	Portable Network Graphics	Einbindung in Wiki		Ergebnisse von Datenanalysen
> `img/plots/`	[`COV_EXP_outlier.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/COV_EXP_outlier.png)	Portable Network Graphics	Einbindung in Wiki		Ergebnisse von Datenanalysen
> `img/plots/`	[`ENCOUNTERCLASS_by_disease.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/ENCOUNTERCLASS_by_disease.png)	Portable Network Graphics	Einbindung in Wiki		Ergebnisse von Datenanalysen
> `src/`	[`public_datawarehouse_connection.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/public_datawarehouse_connection.py)	Python	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Öffentliche Daten	Datenbankinitialisierung Öffentlichkeit ([Data Warehouse](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Mappingtabelle_Gesamt))
> `src/`	[`source_database_implementation.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/source_database_implementation.py)	Python	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Quelldaten	Datenbankinitialisierung Projektverantwortliche ([Source DB](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#datenbank-implementierung))
> `tools/`	[`ETL_create_view_central.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/ETL_create_view_central.sql)	SQL	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Quelldaten	Datenbankinitialisierung Projektverantwortliche ([ETL-Prozess](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenbereinigung-im-ETL-Prozess))
> `tools/`	[`ETL_process.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/ETL_process.py)	Python	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Quelldaten (Öffentliche Daten werden erzeugt)	Datenbankinitialisierung Projektverantwortliche ([ETL-Prozess](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenbereinigung-im-ETL-Prozess))
> `tools/`	[`create_statements_source_db.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/create_statements_source_db.sql)	SQL	Einbindung in [`source_database_implementation.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/source_database_implementation.py)	Quelldaten	Datenbankinitialisierung Projektverantwortliche ([Source DB](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#datenbank-implementierung))
> `tools/`	[`data_clearing_SQL_queries.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/data_clearing_SQL_queries.py)	Python	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Quelldaten	Dokumentation [Datenqualität](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenqualit%C3%A4t#identifikation-von-redundanzen-und-unstimmigkeiten---data-clearing)
> `tools/`	[`data_quality_delete_outlier.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/data_quality_delete_outlier.sql)	SQL	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Öffentliche Daten	[Datenqualität](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenqualit%C3%A4t#identifikation-von-fehlern-und-ausrei%C3%9Fern-in-der-datenbasis---preliminary-data-analysis)

@Carmen-Haubold wo könnte diese Tabelle gut eingefügt werden?

**Comment by lknegendorf** [comment]
> > Mein Vorschlag:
> > ### Übersicht GitHub Repository [`Fuenfgeld/ATeamDatenmanagementUndArchivierung`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung)
> > Pfad	Dateiname	Sprache/Dateiformat	Ausführungsumgebung	Datenzugriff	Zweck
> > .	[`IMECOS_master.ipynb`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Jupyter Notebook	Google Colab	Quelldaten und Öffentliche Daten möglich	Colab Book Masterfile ([System-Umgebung](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/System-Umgebung))
> > .	[`LICENSE`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/LICENSE)		GitHub		Repository Lizenz: MIT License
> > .	[`README.md`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/README.md)	Markdown Language	GitHub		Repository Readme
> > `build/`	.gitignore		GitHub		GitHub Systemdatei
> > `docs/`	[`ER_model_of_data_warehouse.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ER_model_of_data_warehouse.svg)	Scalable Vector Graphics	Einbindung in Wiki		Graphische Dokumentation
> > `docs/`	[`ER_model_of_source_data.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ER_model_of_source_data.svg)	Scalable Vector Graphics	Einbindung in Wiki		Graphische Dokumentation
> > `docs/`	[`ETL_Mapping.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ETL_Mapping.svg)	Scalable Vector Graphics	Einbindung in Wiki		Graphische Dokumentation
> > `docs/`	[`ETL_view_on_source_data.svg`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/docs/ETL_view_on_source_data.svg)	Scalable Vector Graphics	Einbindung in Wiki		Graphische Dokumentation
> > `img/plots/`	[`COV_EXP_distribution_by_disease.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/COV_EXP_distribution_by_disease.png)	Portable Network Graphics	Einbindung in Wiki		Ergebnisse von Datenanalysen
> > `img/plots/`	[`COV_EXP_outlier.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/COV_EXP_outlier.png)	Portable Network Graphics	Einbindung in Wiki		Ergebnisse von Datenanalysen
> > `img/plots/`	[`ENCOUNTERCLASS_by_disease.png`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/img/plots/ENCOUNTERCLASS_by_disease.png)	Portable Network Graphics	Einbindung in Wiki		Ergebnisse von Datenanalysen
> > `src/`	[`public_datawarehouse_connection.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/public_datawarehouse_connection.py)	Python	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Öffentliche Daten	Datenbankinitialisierung Öffentlichkeit ([Data Warehouse](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Mappingtabelle_Gesamt))
> > `src/`	[`source_database_implementation.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/source_database_implementation.py)	Python	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Quelldaten	Datenbankinitialisierung Projektverantwortliche ([Source DB](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#datenbank-implementierung))
> > `tools/`	[`ETL_create_view_central.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/ETL_create_view_central.sql)	SQL	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Quelldaten	Datenbankinitialisierung Projektverantwortliche ([ETL-Prozess](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenbereinigung-im-ETL-Prozess))
> > `tools/`	[`ETL_process.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/ETL_process.py)	Python	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Quelldaten (Öffentliche Daten werden erzeugt)	Datenbankinitialisierung Projektverantwortliche ([ETL-Prozess](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenbereinigung-im-ETL-Prozess))
> > `tools/`	[`create_statements_source_db.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/create_statements_source_db.sql)	SQL	Einbindung in [`source_database_implementation.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/src/source_database_implementation.py)	Quelldaten	Datenbankinitialisierung Projektverantwortliche ([Source DB](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#datenbank-implementierung))
> > `tools/`	[`data_clearing_SQL_queries.py`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/data_clearing_SQL_queries.py)	Python	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Quelldaten	Dokumentation [Datenqualität](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenqualit%C3%A4t#identifikation-von-redundanzen-und-unstimmigkeiten---data-clearing)
> > `tools/`	[`data_quality_delete_outlier.sql`](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/tools/data_quality_delete_outlier.sql)	SQL	Einbindung in [Colab Book Masterfile](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb)	Öffentliche Daten	[Datenqualität](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenqualit%C3%A4t#identifikation-von-fehlern-und-ausrei%C3%9Fern-in-der-datenbasis---preliminary-data-analysis)
> 
> @Carmen-Haubold wo könnte diese Tabelle gut eingefügt werden?

Hab es erstmal ganz am Ende eingefügt, kann aber auch gerne noch woanders hin ;)

**Comment by Carmen-Haubold** [comment]
Hallo Leo,

wie wäre eine eigene Übersichtsseite im Wiki?
Wenn ich hierbei helfen kann, gerne.

Grüße Carmen

**Comment by lknegendorf** [comment]
> Hallo Leo,
> 
> wie wäre eine eigene Übersichtsseite im Wiki?
> Wenn ich hierbei helfen kann, gerne.
> 
> Grüße Carmen

Ja finde ich super, danke dir schonmal !

**Comment by Carmen-Haubold** [comment]
![Übersicht_GitHub_Repository](https://user-images.githubusercontent.com/77020590/107572475-a2a35880-6bec-11eb-9fa8-5f229f48ff25.jpg)

Die Übersicht ist jetzt ein Unterpunkt vom Datenmanagementplan.
Kann das Issue geschlossen werden?
