### ISSUE TITLE
Set up the project wiki

### ISSUE THREAD

**Issue by lknegendorf** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#5]
The wiki should contain the template of the datamanagement plan

**Comment by fphans** [comment]
Leo, thanks for your effort! Will be back in the office thursday. Shall we meet friday 18oohrs again?

**Comment by lknegendorf** [comment]
> Leo, thanks for your effort! Will be back in the office thursday. Shall we meet friday 18oohrs again?

No problem. I'm working late shift on Friday, so for me 5p.m. would be better because I have to do direct microscopies at 6. @Carmen-Haubold how are you scheduled on Friday?
Do we want to participate in the group discussion on Google Meet and if so, when is it?

**Comment by Carmen-Haubold** [comment]
Hi Leo,

am Freitag, um 17:00 Uhr, kann ich auch teilnehmen (keine Termine).

Gruß Carmen

Am Mi., 13. Jan. 2021 um 15:55 Uhr schrieb lknegendorf <
notifications@github.com>:

**Comment by fphans** [comment]
wiki heute übersetzt 99% und Links genreriert. @lknegendorf close?
