### ISSUE TITLE
Alternativer Code zum start post ETL

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#50]
Für das öffentliche colabbook brauchen wir alternativen Start zur Analyse post ETL (damit CSV nicht public sein müssen)

**Comment by fphans** [comment]
habe versuch vor dem etl prozess eine sql connection auf das shared drive zu etablieren, was auch funktioniert.

Problem: Code findet die "tb_*" files dann nicht mehr weil auf anderer conn gesucht wird

**Comment by lknegendorf** [comment]
> habe versuch vor dem etl prozess eine sql connection auf das shared drive zu etablieren, was auch funktioniert.
> 
> Problem: Code findet die "tb_*" files dann nicht mehr weil auf anderer conn gesucht wird

Magst du mir den Pfad des Colabbooks mit richtigem Branch hier verlinken, dann schaue ich das morgen mal an, wenn du es noch nicht fertig hast.
Du hast eine neue Methode gebaut dafür oder? Weil die bisherige Definition erzeugt ja nur welche im Memory.
Dass man auf die 'tb_' Tabellen nicht zugreifen kann ist auf jeden Fall gewünscht, da stehen ja die Patientendaten drin auf die die Öffentlichkeit keinen Zugriff haben soll. Also später für die Datenanalyse brauchen wir dann nur das Data Warehouse (also die vier Tabellen ohne 'tb_')

BG Leo

**Comment by fphans** [comment]
der etl prozess braucht hallt die conn zur "memory" db soll aber in shared exportieren

**Comment by lknegendorf** [comment]
Achso und die Database muss zum Ende des ETL Prozess eröffnet werden, also beim "L", weil die Daten da ja erst geladen werden, hast du das mitbedacht? Weil durch das Transform und die Speicherung der Tabellen in der Pipeline brauchst du zu dem Zeitpunkt die Source DB nicht mehr.

**Comment by lknegendorf** [comment]
> der etl prozess braucht hallt die conn zur "memory" db soll aber in shared exportieren

Genau, darum hat er ja die 'conn_new'. Die musst du eigentlich nur statt im Memory im Drive erzeugen.

**Comment by fphans** [comment]
vll ist das doch zu hoch für mich ;-) habe jetzt ein alternativ-file laufen lassen nur auf den shared drive bezogen. ausser der initialen db wird dort aber nicht ausgegeben...

[alt_db_master](https://colab.research.google.com/drive/1H95pxAt_KPElNY2_m1l9yUlplqWN893r?usp=sharing)

**Comment by lknegendorf** [comment]
@fphans Jo ist fertig im Master, Anleitung muss dann noch in #44 beschrieben werden.
