### ISSUE TITLE
Prüfungsskript

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#51]
Reihenfolge und Zuständigkeiten:

Link zu G-Drive: [Prüfungsskript](https://docs.google.com/document/d/1YDhYejG8VqZ4ELYUq4IiDWTvD5wDTr78eiw0a1jPMF0/edit?usp=sharing)

**Comment by lknegendorf** [comment]
@fphans @Carmen-Haubold Link zum Prüfungsskript ist eingefügt (siehe oben)

**Comment by lknegendorf** [comment]
@fphans @Carmen-Haubold Link zum Prüfungsskript ist eingefügt (siehe oben)

**Comment by fphans** [comment]
Great Leo, danke!

**Comment by fphans** [comment]
please check changes @Carmen-Haubold @lknegendorf

**Comment by lknegendorf** [comment]
> please check changes @Carmen-Haubold @lknegendorf

Cool, vielen Dank! Habe noch einen Änderungswunsch, teile ich euch nachher bei der Besprechung mit ;)

**Comment by lknegendorf** [comment]
Es fehlt noch: 

- [x] Datenfluss-Diagramm (idealerweise mit Verlinkungen)
- [ ] Forschungsergebnisse im Master

**Comment by fphans** [comment]
@lknegendorf skript angepasst, bitte prüfen

**Comment by lknegendorf** [comment]
> @lknegendorf skript angepasst, bitte prüfen

Jo finde ich gut so, erstmal. Müssen sicher nach heute noch was anpassen.

**Comment by lknegendorf** [comment]
Machen wir so wie heute besprochen!
