### ISSUE TITLE
Verlinkung

### ISSUE THREAD

**Issue by Carmen-Haubold** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#53]
In [Datenqualität](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Datenqualit%C3%A4t)
 führt der zweite "[hier](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/data_clearing_SQL_queries.py)"-Link nicht zu der gewünschten Seite.

![Datenqualität_Link](https://user-images.githubusercontent.com/77020590/107155266-c90c8e00-6977-11eb-8528-9395fc49e3e5.jpg)

**Comment by lknegendorf** [comment]
Check!
