### ISSUE TITLE
master file compilieren

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#57]
die analysen aus den einzelnen branches mit erklärungen in master einpflegen. ggf architektur über einzelne *.py files im repository wegen übersichtlichkeit

**Comment by fphans** [comment]
die altersverteilung hast du galueb ich rausgenonmmen. absicht? dann sollten wir die überschriften noch anpassen

**Comment by lknegendorf** [comment]
> die altersverteilung hast du galueb ich rausgenonmmen. absicht? dann sollten wir die überschriften noch anpassen

Keine Absicht, ich hatte noch nicht an der compilierung gearbeitet. Kann gerne wieder rein

**Comment by lknegendorf** [comment]
@fphans eine Sache noch, wollen wir diese Korrelationsanalysen aus meinem Branch auch noch bei Forschungsfrage 1 ins Master einbauen (hatte das ja mal ganz am Anfang gemacht), passt das noch irgendwo rein?
![image](https://user-images.githubusercontent.com/77101575/107876142-7b86a880-6ec4-11eb-85b5-621d40285d93.png)
![image](https://user-images.githubusercontent.com/77101575/107876167-96591d00-6ec4-11eb-9e41-fb7144505943.png)
![image](https://user-images.githubusercontent.com/77101575/107876171-9f49ee80-6ec4-11eb-8e0a-2c2952141900.png)

**Comment by lknegendorf** [comment]
Würde auch vielleicht diese Zelle https://colab.research.google.com/github/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/main/IMECOS_master.ipynb#scrollTo=-DWJDc2tUuvd&line=3&uniqifier=1 rausnehmen, weil die Grafik ja bei Hypothese 3 dann nochmal erzeugt wird
steht `# is saved later at Hyp3` aktuell drunter, damit du weißt wo ichs meine

**Comment by fphans** [comment]
ich finde die regressionen super, ich komme aber realistischerweise nicht mehr dazu das einzuarbeiten. heben wirs uns für das nächste projekt auf?
