### ISSUE TITLE
Datenflussdiagramm

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#58]
if possible für #51

**Comment by lknegendorf** [comment]
@fphans @Carmen-Haubold mal kurz ein aktueller Zwischenstand, was so meine Idee ist arbeite erstmal ein bisschen daran weiter, kann man später ja auch noch anpassen.

![](https://raw.githubusercontent.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/flussdiagramm_temp/img/visual_project_abstract.svg)

**Comment by lknegendorf** [comment]
OK ist in der ersten Version fertig und Links funktionieren auch
