### ISSUE TITLE
felix_branch defekt nach master update

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#59]
hi leo, ich kann unter meinem banch nicht mehr testen, da jetzt nur noch der neue ETL job läuft und ich keine Memory DWH tabellen mehr habe.

wie wprdest du das lösen?

**Comment by lknegendorf** [comment]
> hi leo, ich kann unter meinem banch nicht mehr testen, da jetzt nur noch der neue ETL job läuft und ich keine Memory DWH tabellen mehr habe.
> 
> wie wprdest du das lösen?

Hi Felix,

du brauchst doch keine Memory DWH, die Bezeichnungen conn_new und so gelten ja auch für das lokale DWH..
In deinem branch_felix da im Master steht der richtige Code..
Wo arbeitest du denn gerade? Wenn die folgenden drei Dateien ausgeführt werden, dann muss es immer funktionieren:

import requests
exec(requests.get('https://raw.githubusercontent.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/main/src/source_database_implementation.py').text)
cur.executescript(requests.get('https://raw.githubusercontent.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/main/tools/ETL_create_view_central.sql').text)
conn.commit()
exec(requests.get('https://raw.githubusercontent.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/main/tools/ETL_process.py').text)

Sonst bräuchte ich eine genauere Fehlerbeschreibung leider erstmal ;)
BG Leo

**Comment by fphans** [comment]
Hi Leo,

Danke für Deine Rückmeldung. Ich weiss nicht woran es liegt aber die Spielwiese ist irgendwie futsch. ich committe gleich mal das master in meinen branch mit meinen Änderungen

konkrete frage:
Seit dem neuem Skript kommen andere Ergebnisse raus. Ich bekomme plötzlich starke Korrelationen für den Familienstand z.b. Könntest Du da einmal mit rein schauen? Ich habe das jetzt erst mal unter Hypothese 1 eingebaut

**Comment by fphans** [comment]
spezielles Augenmerk: SQL Abfrage des Marital SQL-codes...

**Comment by lknegendorf** [comment]
Gibst du mir einen direkten Link zu einer Datei, die ich anschauen soll?
Dann kann ich morgen mal draufgucken.

**Comment by fphans** [comment]
[latest master](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/branch_felix/IMECOS_master.ipynb)

**Comment by lknegendorf** [comment]
> spezielles Augenmerk: SQL Abfrage des Marital SQL-codes...

Ok da schonmal: Wenn du beim Marital Code im pandas.DataFrame 'None' siehst, ist das wie Null in SQL, müsstest also, wenn du das so haben willst
`WHEN marital IS NULL`
            `THEN 1`
in der SQL Abfrage eintragen.

**Comment by lknegendorf** [comment]
![image](https://user-images.githubusercontent.com/77101575/107325485-19840880-6aaa-11eb-887d-fa19b8842951.png)

Das ist mal geplottet x->y | ML_marital_code -> COV_EXP_RATIO, kann also schon sein, dass diese Korrelation stimmt.

Vielleicht wäre noch eine Idee, die Null-Werte ganz rauszunehmen und dann nochmal durchzujagen?

Hoffe, das hilft beides erstmal weiter.
Beste Grüße
Leo

**Comment by lknegendorf** [comment]
Sonst passt alles ;)

**Comment by lknegendorf** [comment]
> [latest master](https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/branch_felix/IMECOS_master.ipynb)

@fphans beim ML ist da noch ein kleiner Denkfehler drin, an sich ist das richtig, aber du findest die Antwort auf eine andere Frage, als die die du gestellt hast. Wenn du Zeit hast kannst du mich anrufen dann können wir es vielleicht besser besprechen.

**Comment by lknegendorf** [comment]
OK das war ja dann jetzt auch fertig durch den Export des Decision Tree
