### ISSUE TITLE
Datenmanagement Feedback 

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#62]
Hi Zusammen wie versprochen nochmal der Feedback von Kerstin Stand letztes Wochenende 
zum Datenmanagementplan und der Verkettung zu den vorliegen Daten (Team A):
3.1: 
* Referenz zu Studienprotokoll herstellen (normalerweise)
* Referenz zum Mapping herstellen
* wurde ein Coding von Daten durchgeführt?
* Maßnahmen zur Herstellung der Interoperabilität von Datensätzen
* Maßnahmen zur Datenbereinigung: man kann jetzt nur noch über 'Ausreißer Daten' berichten und erklären wie man mit diesen in der Auswertung umgeht. Bereinigen geht ja nicht bei synthetischen Daten
* die Datenverarbeitungsschritte erklären, auch wie die Pseudonymisierung umgesetzt wird
* gibt es eine kurze Beschreibung, was und wie man auswerten möchte, welche Programme erzeugt wurden? Die Ergebnisse werden ja ausführlich dargestellt, aber wie kommt man dahin: Software, Version, Umgebung? (wobei man die Ergebnisse im Datenmanagementplan nicht darstellt)
3.3:
* welche (Ergebnis-)files werden erzeugt? Was passiert mit diesen? (in SAS gibt es eine Prozedur proc-contents mit der man sich die Metadaten zu den Daten automatisch erzeugen kann - gibt es so etwas ähnliches in python?)
* Referenz auf GitHub Doku

**Comment by lknegendorf** [comment]
Meines Erachtens sind alle Punkte umgesetzt bis auf diesen:
* welche (Ergebnis-)files werden erzeugt? Was passiert mit diesen? (in SAS gibt es eine Prozedur proc-contents mit der man sich die Metadaten zu den Daten automatisch erzeugen kann - gibt es so etwas ähnliches in python?)

@fphans @Carmen-Haubold bitte einmal prüfen.

**Comment by lknegendorf** [comment]
> Meines Erachtens sind alle Punkte umgesetzt bis auf diesen:
> 
> * welche (Ergebnis-)files werden erzeugt? Was passiert mit diesen? (in SAS gibt es eine Prozedur proc-contents mit der man sich die Metadaten zu den Daten automatisch erzeugen kann - gibt es so etwas ähnliches in python?)
> 
> @fphans @Carmen-Haubold bitte einmal prüfen.

Was machen wir mit dem genannten Punkt, der noch fehlt?

**Comment by fphans** [comment]
das müssen wir wahrscheinlich nach dem meeting machen. ich bin heute an diese n neuen elenenten verzweifelt. das master war nicht mehr zu starten...

**Comment by lknegendorf** [comment]
Wird jetzt nur auf Versionierung und FAIR-Kriterien im Archivkonzept hingewiesen. Denke, das reicht so.

**Comment by fphans** [comment]
danke!
