### ISSUE TITLE
Linkfunktionalität

### ISSUE THREAD

**Issue by Carmen-Haubold** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#63]
Hallo,

habt ihr eine Idee warum dieser Link nicht zu der Überschrift führt?
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#%C3%9Cberblick-datentypen-und-schl%C3%BCsselbeziehungen

Vielen Dank.

LG Carmen

**Comment by lknegendorf** [comment]
> Hallo,
> 
> habt ihr eine Idee warum dieser Link nicht zu der Überschrift führt?
> https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#%C3%9Cberblick-datentypen-und-schl%C3%BCsselbeziehungen
> 
> Vielen Dank.
> 
> LG Carmen

Hi @Carmen-Haubold das liegt daran, dass die Überschrift mit 'Ü' beginnt und das System das irgendwie nicht erkennen kann.
Hab es jetzt einfach auf "Datentypen und Schlüsselbeziehungen" geändert.
Der Link ist: https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/Quelldatenmodell#datentypen-und-schl%C3%BCsselbeziehungen

**Comment by Carmen-Haubold** [comment]
Vielen Dank. Da wäre ich nie drauf gekommen... Jetzt funktioniert der Link.
