### ISSUE TITLE
cape_privacy

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#65]
what and why is it?

**Comment by fphans** [comment]
spielwiese dadurch lahmgelegt ich arbeite jetzt einfach auf main weiter ;-)

**Comment by lknegendorf** [comment]
Das ist die Pseudonymisierung siehe #62

**Comment by lknegendorf** [comment]
> spielwiese dadurch lahmgelegt ich arbeite jetzt einfach auf main weiter ;-)

Um die Spielwiese zu aktivieren, musst du wenn du startest einmal in einer neuen Zelle

`pip install cape_privacy`

ausführen und den Anweisungen da folgen.

**Comment by fphans** [comment]
check
