### ISSUE TITLE
hypothese 1

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#67]
gefragt war:
1. Die Anzahl der Impfungen von Patient*innen korreliert negativ mit der Anzahl von notfallmäßigen Vorstellungen in einem Krankenhaus.

beantwortrt haben wir ob die sozioökonomischen parameter die anzahl der impfunegn vorhersagen kann.

--> Hypothese oder Analyse ändern?

**Comment by lknegendorf** [comment]
> gefragt war:
> 
> 1. Die Anzahl der Impfungen von Patient*innen korreliert negativ mit der Anzahl von notfallmäßigen Vorstellungen in einem Krankenhaus.
> 
> beantwortrt haben wir ob die sozioökonomischen parameter die anzahl der impfunegn vorhersagen kann.
> 
> --> Hypothese oder Analyse ändern?

Ich hab da in meinem Branch ne fertige Auswertung für Frage 1, siehe
https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/blob/branch_leo/IMECOS_master.ipynb

Kannst du einfügen oder ich mache es morgen, siehe #57 (habe daran noch nicht gearbeitet)

Können deine Antwort aber als Frage 2 nehmen, oder?

**Comment by fphans** [comment]
hm guck mal jetzt in den master, ich finde man kann durch die fehlende korrelation die hypothese eientlich widerlegen. si fände ichs rund, ich gucke aber noch in deinen branch ;-)

**Comment by lknegendorf** [comment]
> hm guck mal jetzt in den master, ich finde man kann durch die fehlende korrelation die hypothese eientlich widerlegen. si fände ichs rund, ich gucke aber noch in deinen branch ;-)

Hab jetzt nur mal grob drüber geguckt. Richtig gut! So hab ich es mir vorgestellt, aber man kann die Hypothesen da tatsächlich dann noch anpassen damit es logisch ist.
Vielleicht kannst du mir jetzt am Wochenende nochmal genau den ML Ablauf erklären. 😉
