### ISSUE TITLE
GitHub Übersicht im Wiki aktualisieren

### ISSUE THREAD

**Issue by lknegendorf** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#68]
Hier müssen alle noch hochgeladenen Plots noch ergänzt werden.

https://github.com/Fuenfgeld/ATeamDatenmanagementUndArchivierung/wiki/%C3%9Cbersicht-GitHub-Repository

**Comment by lknegendorf** [comment]
Alle im aktuellen Master hochgeladenen Plots sind drin.
@fphans falls du noch was für Hyp2 hochlädtst bitte eintragen

**Comment by fphans** [comment]
denke wir lassens gut sein
