### ISSUE TITLE
Verständnis crosslink zwischen Dataframe Pandas und Tabelle/SQL

### ISSUE THREAD

**Issue by fphans** [Fuenfgeld/ATeamDatenmanagementUndArchivierung#9]
Liebe Carmen, lieber Leo,

ich verstehen nicht wie wir die datenmanipulation am besten machen. Aus dem CSV ein Dataframe machen ist ja schnell passiert. So können wir ja aber keine SQL Abfragen laufen lassen wenn ich das richtig verstehe. Wie kommen die CSVs dann in die Tabellen?

Lg

Felix

**Comment by lknegendorf** [comment]
Hi @fphans,
können das heute Abend nochmal genau durchsprechen. Es ist so gedacht, dass wir die .csv-Rohdaten in eine Datenbank laden (das hast du letzte Woche vorbereitet), ich würde dann vorschlagen, dass wir aus dieser heraus mit SQL Abfragen unser Sternschema in Dataframes hinein speichern, in dieses dann mit Python die Datentranformation machen und die transformierten Daten dann wieder in eine neue Datenbank speichern, diese wird dann als Grundlage für die Analysen im Rahmen des Projektes dienen.

**Comment by lknegendorf** [comment]
Hi,
habe als Ergänzung zu dem, was wir gestern erarbeitet hatten, eine noch einfachere Möglichkeit gefunden (war weiter unten in einem der Links aus der Musterlösung, obwohl in der Musterlösung anders gelöst -> [Referenz](https://stackoverflow.com/questions/2887878/importing-a-csv-file-into-a-sqlite3-database-table-using-python
).
_**df = pandas.read_csv(csvfile)
df.to_sql(table_name, conn, if_exists='append', index=False)**_

**Comment by fphans** [comment]
das ist ja elegant!!
